#!/bin/bash

inGitChatRepo () {
	# Check that we're in a git repo
	if [ ! -d ".git" ]; then
		return 1
	fi

	# Check that it's a GitChat repo
	if [ ! -f ".gitchat" ]; then
		return 1
	fi

	return 0
}

ACTION=$1

# Action args start at $2
if [ "$ACTION" = "new-chat" ]; then
	CHATNAME="$2"

	if [ "$CHATNAME" = "" ]; then
		# Replace with more robust check!
		echo "Chat name required"
		exit 1
	fi

	git init $CHATNAME
	:>| $CHATNAME/.gitchat	

elif [ "$ACTION" = "new-message" ]; then
	if ! inGitChatRepo; then
		echo "Not in git chat repo! Create one with 'git-chat new-chat foo'"
		exit 1
	fi

	MESSAGE="$2"

	if [ "$MESSAGE" = "" ]; then
		echo "Message required!"
		exit 1
	fi

	git commit --allow-empty -m "$MESSAGE"
elif [ "$ACTION" = "show-messages" ]; then
	if ! inGitChatRepo; then
		echo "Not in git chat repo! Create one with 'git-chat new-chat foo'"
		exit 1	
	fi

	git log --pretty=format:"%h - %an, %ar : %s"
fi
