#!/bin/bash

inGitChatRepo () {
	# Check that we're in a git repo
	if [ ! -d ".git" ]; then
		return 1
	fi

	# Check that it's a GitChat repo
	if [ ! -f ".gitchat" ]; then
		return 1
	fi

	return 0
}

ACTION=$1

# Action args start at $2
if [ "$ACTION" = "help" ]; then
	echo "git-chat new-chat <CHATNAME> <UPSTREAM>"
	echo "git-chat clone-chat <UPSTREAM>"
	echo "git-chat new-message <MESSAGE>"
	echo "git-chat show-messages"

elif [ "$ACTION" = "new-chat" ]; then
	# Initialize local repo and remote
	CHATNAME="$2"
	UPSTREAM="$3"

	if [ "$CHATNAME" = "" ]; then
		# Replace with more robust check!
		echo "Chat name required"
		exit 1
	fi

	if [ "$UPSTREAM" = "" ]; then
		echo "Upstream required"
	fi

	git init $CHATNAME
	pushd $CHATNAME
		:>| .gitchat
		git commit --allow-empty -m "New git chat"
		git remote add origin "$UPSTREAM"
		git push -u origin master
		git branch --set-upstream-to=origin/master master
	popd	

elif [ "$ACTION" = "clone-chat" ]; then
	UPSTREAM="$2"

	if [ "$UPSTREAM" = "" ]; then
		echo "Upstream URL required!"
		exit 1
	fi

	git clone "$UPSTREAM"

elif [ "$ACTION" = "new-message" ]; then
	if ! inGitChatRepo; then
		echo "Not in git chat repo! Create one with 'git-chat new-chat foo'"
		exit 1
	fi

	MESSAGE="$2"

	if [ "$MESSAGE" = "" ]; then
		echo "Message required!"
		exit 1
	fi
	git pull
	git commit --allow-empty -m "$MESSAGE"
	git push

elif [ "$ACTION" = "show-messages" ]; then
	if ! inGitChatRepo; then
		echo "Not in git chat repo! Create one with 'git-chat new-chat foo'"
		exit 1	
	fi

	git pull
	git log --reverse --pretty=format:"%h - %an, %ar : %s"
fi
